//! The embedded coastline asset (WO-020 plan D12) — Natural Earth 110m land, simplified by
//! `tools/make_coastline.py` to ≤ 3 500 points and embedded in the wasm data section.
//!
//! The MAP renderers need geography, and the display vocabulary has no image primitive by design
//! (ADR-010 d3), so coastlines ride [`crate::ir::PathItem`]s — which means the geometry must be
//! small enough to embed. It is: the asset is ~15 KB (4 bytes/point, centidegree `i16` pairs), an
//! order of magnitude inside the 160 KB budget, and `include_bytes!` puts it in the component's
//! data section with no hash-declared asset store (MODULE-BUILD-GUIDE §3's small-asset rule).
//!
//! The format is documented in `tools/make_coastline.py`; the reader here is dependency-free
//! (manual little-endian decode — wasm32 is LE). A malformed asset is refused in words at
//! [`Coastline::parse`], never misread: the coastline is the one piece of instrument state that is
//! compiled in, so a bad byte is a build defect the reader must surface, not paper over.

/// The asset bytes, embedded at compile time (D12). Regenerated by `tools/make_coastline.py`;
/// the `--check` gate and the harness's asset test keep the file and this reader honest.
pub static ASSET: &[u8] = include_bytes!("../../assets/coastline-110m.bin");

/// The asset magic (`"SPRQ"` little-endian), mirrored from the generator.
pub const MAGIC: u32 = 0x5350_5251;
/// The asset format version this reader understands.
pub const VERSION: u32 = 1;

/// One coastline ring: a closed land-mass boundary as (lon, lat) degrees, west→east, south→north.
/// The ring is implicitly closed (the last point joins the first; the closing point is not stored).
pub type Ring = Vec<(f64, f64)>;

/// The decoded coastline: every land ring, in asset order.
#[derive(Clone, Debug, PartialEq)]
pub struct Coastline {
    rings: Vec<Ring>,
    point_count: usize,
}

/// A little-endian `u32` at `off`, or `None` past the end.
fn u32_at(b: &[u8], off: usize) -> Option<u32> {
    let s = b.get(off..off + 4)?;
    Some(u32::from_le_bytes([s[0], s[1], s[2], s[3]]))
}

/// A little-endian `i16` at `off`, or `None` past the end.
fn i16_at(b: &[u8], off: usize) -> Option<i16> {
    let s = b.get(off..off + 2)?;
    Some(i16::from_le_bytes([s[0], s[1]]))
}

impl Coastline {
    /// Parses the embedded [`ASSET`]. This is the normal path — the asset is compiled in, so a
    /// failure here is a build defect (a stale or corrupt `coastline-110m.bin`), surfaced in words.
    ///
    /// # Errors
    /// A string naming the defect (bad magic, unknown version, truncated ring) when the asset does
    /// not match the documented format.
    pub fn from_asset() -> Result<Self, String> {
        Self::parse(ASSET)
    }

    /// Parses asset bytes in the documented format.
    ///
    /// # Errors
    /// A string naming the defect when the bytes are not a well-formed coastline asset.
    pub fn parse(b: &[u8]) -> Result<Self, String> {
        let magic = u32_at(b, 0).ok_or("coastline asset truncated before the magic")?;
        if magic != MAGIC {
            return Err(format!(
                "coastline asset magic {magic:#010x} != {MAGIC:#010x} (\"SPRQ\") — \
                 not a make_coastline.py asset"
            ));
        }
        let version = u32_at(b, 4).ok_or("coastline asset truncated before the version")?;
        if version != VERSION {
            return Err(format!(
                "coastline asset version {version} != {VERSION} — regenerate with \
                 tools/make_coastline.py or teach this reader the new layout"
            ));
        }
        let ring_count =
            u32_at(b, 8).ok_or("coastline asset truncated before the ring count")? as usize;
        let mut off = 12usize;
        let mut rings = Vec::with_capacity(ring_count);
        let mut point_count = 0usize;
        for r in 0..ring_count {
            let n = u32_at(b, off).ok_or(format!("ring {r}: truncated before its point count"))?
                as usize;
            off += 4;
            if n < 3 {
                return Err(format!(
                    "ring {r}: {n} points < 3 — a ring must be a drawable polygon"
                ));
            }
            let mut ring = Vec::with_capacity(n);
            for p in 0..n {
                let lon = i16_at(b, off).ok_or(format!("ring {r} point {p}: truncated lon"))?;
                let lat = i16_at(b, off + 2).ok_or(format!("ring {r} point {p}: truncated lat"))?;
                off += 4;
                ring.push((f64::from(lon) / 100.0, f64::from(lat) / 100.0));
            }
            point_count += n;
            rings.push(ring);
        }
        if off != b.len() {
            return Err(format!(
                "coastline asset has {trailing} trailing byte(s) after {ring_count} rings — \
                 the file and the reader disagree on the format",
                trailing = b.len() - off
            ));
        }
        Ok(Self { rings, point_count })
    }

    /// The land rings, in asset order.
    #[must_use]
    pub fn rings(&self) -> &[Ring] {
        &self.rings
    }

    /// The ring count.
    #[must_use]
    pub fn ring_count(&self) -> usize {
        self.rings.len()
    }

    /// The total point count across all rings (the budget number D12 caps at ~3 500).
    #[must_use]
    pub fn point_count(&self) -> usize {
        self.point_count
    }

    /// An empty coastline (no rings) — the honest fallback if a caller chooses to render without
    /// geography rather than refuse. The Observatory does not use this in v1 (the asset is compiled
    /// in and its parse failure is a build defect), but the renderers take `&Coastline` and a test
    /// may want the empty case. For a `&'static` empty coastline see [`EMPTY`].
    #[must_use]
    pub const fn empty() -> Self {
        Self { rings: Vec::new(), point_count: 0 }
    }
}

/// The empty coastline as a module-level `static`, so a `RenderCtx` (in a test, or a map-less
/// render) can borrow a `&'static Coastline` without parsing the asset. A `const` would be a
/// temporary the borrow checker cannot return a reference to; a `static` is a real `'static`
/// location. (An associated `static` is not a thing in Rust, hence module-level.)
pub static EMPTY: Coastline = Coastline { rings: Vec::new(), point_count: 0 };

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
    use super::*;

    #[test]
    fn the_embedded_asset_parses() {
        let c = Coastline::from_asset().unwrap();
        assert!(c.ring_count() > 0, "the 110m land set has many rings");
        // D12's budget: <= ~3500 points. The generator targets exactly 3500; assert the cap with a
        // little headroom so a re-record that overshoots is caught here, not at draw.
        assert!(c.point_count() <= 3600, "point budget: {} > 3600", c.point_count());
        // Every ring is a drawable polygon.
        assert!(c.rings().iter().all(|r| r.len() >= 3));
    }

    #[test]
    fn coordinates_are_in_range() {
        let c = Coastline::from_asset().unwrap();
        for ring in c.rings() {
            for &(lon, lat) in ring {
                assert!((-180.0..=180.0).contains(&lon), "lon {lon} out of range");
                assert!((-90.0..=90.0).contains(&lat), "lat {lat} out of range");
            }
        }
    }

    #[test]
    fn a_bad_magic_is_refused_in_words() {
        let e = Coastline::parse(&[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]).unwrap_err();
        assert!(e.contains("magic"), "{e}");
    }

    #[test]
    fn an_unknown_version_is_refused_in_words() {
        // Correct magic, version 99.
        let mut b = Vec::new();
        b.extend_from_slice(&MAGIC.to_le_bytes());
        b.extend_from_slice(&99u32.to_le_bytes());
        b.extend_from_slice(&0u32.to_le_bytes());
        let e = Coastline::parse(&b).unwrap_err();
        assert!(e.contains("version"), "{e}");
    }

    #[test]
    fn a_truncated_ring_is_refused() {
        let mut b = Vec::new();
        b.extend_from_slice(&MAGIC.to_le_bytes());
        b.extend_from_slice(&VERSION.to_le_bytes());
        b.extend_from_slice(&1u32.to_le_bytes()); // one ring
        b.extend_from_slice(&5u32.to_le_bytes()); // ... claiming 5 points
        b.extend_from_slice(&1i16.to_le_bytes()); // but only 1 coord pair present
        b.extend_from_slice(&1i16.to_le_bytes());
        let e = Coastline::parse(&b).unwrap_err();
        assert!(e.contains("truncated"), "{e}");
    }

    #[test]
    fn trailing_bytes_are_a_format_disagreement() {
        let mut b = Vec::new();
        b.extend_from_slice(&MAGIC.to_le_bytes());
        b.extend_from_slice(&VERSION.to_le_bytes());
        b.extend_from_slice(&0u32.to_le_bytes()); // zero rings
        b.push(0xFF); // one stray byte
        let e = Coastline::parse(&b).unwrap_err();
        assert!(e.contains("trailing"), "{e}");
    }
}
