//! The 26 parameters, decoded from the contract's `param-set` into a typed struct.
//!
//! The manifest (generated by `gen_manifest.py`) declares 26 params in a fixed order; the contract
//! delivers them as a `param-set` — a version plus a fixed-order array of f32s, one per param, with
//! no per-value type tag (types.wit): **bool rides 0.0/1.0, enum rides its option index, float rides
//! its declared domain value** ("the manifest's declared domain gives each f32 its meaning, exactly
//! as native" — and the native backbone modules read `ctx.param(i)` raw: `syn/sine` reads Hz,
//! `util/gain` reads a ratio). This module is the Observatory's half of that contract: it maps the
//! positional f32 array onto named fields, clamping floats to their declared domain and rounding
//! enums/bools, so a malformed or partial snapshot degrades to the defaults rather than misdrawing.
//!
//! The param ORDER below is load-bearing: it must match the generated manifest's `[[params]]` order
//! exactly (the contract is positional). The harness drift-tests this against the manifest, so a
//! generator re-order without a matching change here fails a test, never a render.

use crate::layout::Layout;
use crate::streams_table;

/// The param count (the manifest declares exactly this many; the contract caps at 32 — the
/// "26 ≤ 32" arithmetic the plan asks INC3 to prove, asserted in [`tests`]).
pub const PARAM_COUNT: usize = 26;

/// The contract's param cap (`sparq_module_api::params::MAX_PARAMS`), mirrored so the core can
/// assert its own headroom without linking the contract crate (D13: the core is dependency-free).
pub const MAX_PARAMS: usize = 32;

// --- param indices (positional — MUST match the generated manifest's [[params]] order) ----------

/// Index of the first `cell_NN` stream enum (cells occupy `IDX_CELL0 .. IDX_CELL0+16`).
pub const IDX_CELL0: usize = 0;
/// Index of `selected_cell`.
pub const IDX_SELECTED: usize = 16;
/// Index of `layout`.
pub const IDX_LAYOUT: usize = 17;
/// Index of `solo`.
pub const IDX_SOLO: usize = 18;
/// Index of `full`.
pub const IDX_FULL: usize = 19;
/// Index of `ticker`.
pub const IDX_TICKER: usize = 20;
/// Index of `grid`.
pub const IDX_GRID: usize = 21;
/// Index of `pause`.
pub const IDX_PAUSE: usize = 22;
/// Index of `ticker_speed`.
pub const IDX_TICKER_SPEED: usize = 23;
/// Index of `history`.
pub const IDX_HISTORY: usize = 24;
/// Index of `intensity`.
pub const IDX_INTENSITY: usize = 25;

// --- float domains (mirror the generated manifest; the harness drift-tests the two) --------------

/// `ticker_speed` min (×).
pub const TICKER_SPEED_MIN: f32 = 0.2;
/// `ticker_speed` max (×).
pub const TICKER_SPEED_MAX: f32 = 3.0;
/// `history` min, seconds (10 min). The §10 draft said "min"; UNITS is closed and has no minutes,
/// so the generator declares seconds (see gen_manifest.py's header).
pub const HISTORY_MIN_S: f32 = 600.0;
/// `history` max, seconds (7 d).
pub const HISTORY_MAX_S: f32 = 604_800.0;
/// `intensity` min (colormap gain, ×).
pub const INTENSITY_MIN: f32 = 0.5;
/// `intensity` max (×).
pub const INTENSITY_MAX: f32 = 2.0;

/// The decoded parameter state — one field per manifest param, named.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Params {
    /// The 16 cell stream selections, as enum option indices (0 = OFF, 1..=23 = a registry stream).
    /// Only the first `layout.cell_count()` (or the selected one in SOLO) are drawn; the rest are
    /// honestly ignored (§D7).
    pub cells: [usize; 16],
    /// The selected cell (0…15) — the SOLO cell and the one the STREAM picker edits.
    pub selected_cell: usize,
    /// The wall layout.
    pub layout: Layout,
    /// SOLO: the selected cell fills the wall.
    pub solo: bool,
    /// FULL: solo + minimal chrome (the data takes everything).
    pub full: bool,
    /// The global ticker band is shown.
    pub ticker: bool,
    /// Graticules and guides are drawn.
    pub grid: bool,
    /// Motion is frozen (ticker scroll + trace advance pause).
    pub pause: bool,
    /// Ticker scroll speed, ×.
    pub ticker_speed: f32,
    /// History span for timeseries/timeline x-windows, seconds.
    pub history_s: f32,
    /// Colormap intensity gain, ×.
    pub intensity: f32,
}

/// Reads an f32 at `i`, or `fallback` past the end (a partial snapshot degrades, never panics).
fn at(v: &[f32], i: usize, fallback: f32) -> f32 {
    v.get(i).copied().unwrap_or(fallback)
}

/// A bool from the snapshot's 0.0/1.0 convention (≥ 0.5 is on — the native round rule).
fn bool_at(v: &[f32], i: usize, fallback: bool) -> bool {
    match v.get(i) {
        Some(x) => *x >= 0.5,
        None => fallback,
    }
}

/// An enum option index from the snapshot, clamped to `0..=max` (a float index rounds; out-of-range
/// clamps rather than wrapping — an index past the options is a host bug the display survives).
fn enum_at(v: &[f32], i: usize, max: usize, fallback: usize) -> usize {
    match v.get(i) {
        Some(x) => {
            if x.is_finite() {
                (x.round().max(0.0) as usize).min(max)
            } else {
                fallback
            }
        },
        None => fallback,
    }
}

impl Default for Params {
    /// The §5.4 default state — what the instrument shows on load and what `example.sparqpatch`
    /// ships. Layout 4×4 (the full wall), ticker + grid on, solo/full/pause off, the three floats at
    /// their manifest defaults, and the 16 cells filled with the §5.4 domain spread (decoded from
    /// the generated manifest's per-cell defaults via the streams table).
    fn default() -> Self {
        Self {
            cells: default_cells(),
            selected_cell: 0,
            layout: Layout::Grid4x4,
            solo: false,
            full: false,
            ticker: true,
            grid: true,
            pause: false,
            ticker_speed: 1.0,
            history_s: 10_800.0, // 3 h
            intensity: 1.0,
        }
    }
}

/// The §5.4 default cell streams, as option indices. The order is the default state's; each id is
/// resolved to its option index through the generated streams table, so a registry re-order moves
/// the defaults correctly (never a hard-coded index). An id absent from the table (impossible for a
/// generated table + a checked default list, but total anyway) falls back to OFF.
fn default_cells() -> [usize; 16] {
    // The §5.4 default state, in cell order. gen_manifest.py's DEFAULT_CELL_STREAMS is the SAME
    // list; the harness drift-tests the two so they cannot diverge.
    const DEFAULTS: [&str; 16] = [
        "swpc.aurora",
        "geo.quakes-hour",
        "swpc.bz",
        "swpc.wwv",
        "sat.iss",
        "geo.eonet",
        "wx.openmeteo",
        "swpc.kp",
        "swpc.xray-flares",
        "space.neo",
        "wx.tides",
        "wx.alerts",
        "swpc.solar-wind",
        "geo.gdacs",
        "wx.air",
        "space.power",
    ];
    let mut cells = [0usize; 16];
    for (i, id) in DEFAULTS.iter().enumerate() {
        cells[i] = streams_table::option_of_stream(id).unwrap_or(0);
    }
    cells
}

impl Params {
    /// Decodes a contract `param-set` value array (positional f32s) into [`Params`]. Values past the
    /// array's end fall back to the §5.4 defaults; floats clamp to their declared domain; enums and
    /// bools round/clamp per the contract's conventions. Total — never panics, never misdraws on a
    /// partial or malformed snapshot.
    #[must_use]
    pub fn from_values(v: &[f32]) -> Self {
        let d = Self::default();
        let mut cells = [0usize; 16];
        for (i, cell) in cells.iter_mut().enumerate() {
            // Each cell enum has OFF (0) + STREAM_COUNT options; clamp to that range.
            *cell = enum_at(v, IDX_CELL0 + i, streams_table::STREAM_COUNT, d.cells[i]);
        }
        Self {
            cells,
            selected_cell: enum_at(v, IDX_SELECTED, crate::CELL_COUNT - 1, d.selected_cell),
            layout: Layout::from_option(enum_at(
                v,
                IDX_LAYOUT,
                Layout::OPTIONS.len() - 1,
                d.layout.option(),
            )),
            solo: bool_at(v, IDX_SOLO, d.solo),
            full: bool_at(v, IDX_FULL, d.full),
            ticker: bool_at(v, IDX_TICKER, d.ticker),
            grid: bool_at(v, IDX_GRID, d.grid),
            pause: bool_at(v, IDX_PAUSE, d.pause),
            ticker_speed: at(v, IDX_TICKER_SPEED, d.ticker_speed)
                .clamp(TICKER_SPEED_MIN, TICKER_SPEED_MAX),
            history_s: at(v, IDX_HISTORY, d.history_s).clamp(HISTORY_MIN_S, HISTORY_MAX_S),
            intensity: at(v, IDX_INTENSITY, d.intensity).clamp(INTENSITY_MIN, INTENSITY_MAX),
        }
    }

    /// Re-encodes to the positional f32 array the contract's `param-set` carries (the inverse of
    /// [`Self::from_values`], for the state blob and for tests). Length is exactly [`PARAM_COUNT`].
    #[must_use]
    pub fn to_values(&self) -> [f32; PARAM_COUNT] {
        let mut v = [0.0f32; PARAM_COUNT];
        for i in 0..16 {
            v[IDX_CELL0 + i] = self.cells[i] as f32;
        }
        v[IDX_SELECTED] = self.selected_cell as f32;
        v[IDX_LAYOUT] = self.layout.option() as f32;
        v[IDX_SOLO] = self.solo as u8 as f32;
        v[IDX_FULL] = self.full as u8 as f32;
        v[IDX_TICKER] = self.ticker as u8 as f32;
        v[IDX_GRID] = self.grid as u8 as f32;
        v[IDX_PAUSE] = self.pause as u8 as f32;
        v[IDX_TICKER_SPEED] = self.ticker_speed;
        v[IDX_HISTORY] = self.history_s;
        v[IDX_INTENSITY] = self.intensity;
        v
    }

    /// The stream id a cell selects, or `None` for OFF (option 0) / an out-of-range index. This is
    /// the guest-side resolution of the cell enum — the SAME indirection the host performs on the
    /// `stream = "param:cell_NN"` binding (D4), so the guest knows which feed a cell shows.
    #[must_use]
    pub fn cell_stream(&self, cell: usize) -> Option<&'static str> {
        self.cells.get(cell).and_then(|&opt| streams_table::stream_by_option(opt)).map(|m| m.id)
    }

    /// The number of cells the current layout draws (SOLO always draws 1).
    #[must_use]
    pub fn visible_cell_count(&self) -> usize {
        if self.solo {
            1
        } else {
            self.layout.cell_count()
        }
    }

    /// Whether cell `i` is drawn by the current layout (SOLO draws only the selected cell).
    #[must_use]
    pub fn cell_visible(&self, i: usize) -> bool {
        if self.solo {
            i == self.selected_cell
        } else {
            i < self.layout.cell_count()
        }
    }
}

// The plan's "26 ≤ 32" arithmetic, proven AT COMPILE TIME (INC3 test requirement) — a manifest
// that grew past the cap, or an index table that drifted from the count, would fail the build.
const _: () = assert!(PARAM_COUNT <= MAX_PARAMS, "the 26 params must fit the contract's 32 cap");
const _: () = assert!(PARAM_COUNT == 26, "the manifest declares exactly 26 params");
const _: () = assert!(IDX_INTENSITY + 1 == PARAM_COUNT, "the index table must match the count");
const _: () = assert!(IDX_CELL0 + 16 == IDX_SELECTED, "the 16 cell params occupy indices 0..16");

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
    use super::*;

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn the_param_count_is_inside_the_contract_cap() {
        // The runtime face of the compile-time const asserts above.
        assert_eq!(PARAM_COUNT, 26, "the manifest declares 26 params");
        assert!(PARAM_COUNT <= MAX_PARAMS, "26 ≤ the contract's 32-param cap");
        assert_eq!(IDX_INTENSITY, PARAM_COUNT - 1);
        assert_eq!(IDX_CELL0 + 16, IDX_SELECTED);
        // And a decoded set really carries that many values.
        assert_eq!(Params::default().to_values().len(), PARAM_COUNT);
    }

    #[test]
    fn defaults_match_the_5_4_state() {
        let p = Params::default();
        assert_eq!(p.layout, Layout::Grid4x4, "the full wall is the default face");
        assert!(p.ticker && p.grid, "ticker + grid on by default");
        assert!(!p.solo && !p.full && !p.pause);
        assert_eq!(p.ticker_speed, 1.0);
        assert_eq!(p.history_s, 10_800.0);
        assert_eq!(p.intensity, 1.0);
        // The first cell defaults to the aurora (§5.4's map-heat headline).
        assert_eq!(p.cell_stream(0), Some("swpc.aurora"));
        assert_eq!(p.cell_stream(3), Some("swpc.wwv"));
    }

    #[test]
    fn values_round_trip() {
        let mut p = Params::default();
        p.cells[0] = 5;
        p.selected_cell = 7;
        p.layout = Layout::Grid3x3;
        p.solo = true;
        p.ticker_speed = 2.5;
        p.history_s = 3600.0;
        let v = p.to_values();
        let q = Params::from_values(&v);
        assert_eq!(p, q, "from_values(to_values(p)) == p");
    }

    #[test]
    fn floats_clamp_to_their_declared_domain() {
        // A malformed snapshot (out-of-domain float) clamps, never misdraws.
        let mut v = Params::default().to_values();
        v[IDX_HISTORY] = 1e9;
        v[IDX_INTENSITY] = -5.0;
        v[IDX_TICKER_SPEED] = 100.0;
        let p = Params::from_values(&v);
        assert_eq!(p.history_s, HISTORY_MAX_S);
        assert_eq!(p.intensity, INTENSITY_MIN);
        assert_eq!(p.ticker_speed, TICKER_SPEED_MAX);
    }

    #[test]
    fn a_partial_snapshot_falls_back_to_defaults() {
        // Only the first few values present (a truncated param-set): the rest are the §5.4 defaults.
        let p = Params::from_values(&[1.0, 2.0]);
        let d = Params::default();
        assert_eq!(p.cells[0], 1);
        assert_eq!(p.cells[1], 2);
        assert_eq!(p.cells[2], d.cells[2], "cell 3+ fall back to default");
        assert_eq!(p.layout, d.layout);
        assert_eq!(p.ticker, d.ticker);
    }

    #[test]
    fn nan_and_inf_indices_do_not_poison() {
        let mut v = Params::default().to_values();
        v[IDX_SELECTED] = f32::NAN;
        v[IDX_LAYOUT] = f32::INFINITY;
        let p = Params::from_values(&v);
        // A non-finite enum falls back to the default index rather than becoming a wild usize.
        assert_eq!(p.selected_cell, Params::default().selected_cell);
        assert!(p.selected_cell < crate::CELL_COUNT);
    }

    #[test]
    fn cell_stream_resolves_off_to_none() {
        let mut p = Params::default();
        p.cells[0] = 0; // OFF
        assert_eq!(p.cell_stream(0), None, "option 0 is OFF — no stream");
        p.cells[0] = streams_table::STREAM_COUNT + 5; // out of range
        assert_eq!(p.cell_stream(0), None, "an out-of-range option is not a stream");
    }

    #[test]
    fn solo_draws_one_cell_and_the_layout_draws_its_count() {
        let mut p = Params::default();
        assert_eq!(p.visible_cell_count(), 16, "4×4 default");
        p.solo = true;
        p.selected_cell = 9;
        assert_eq!(p.visible_cell_count(), 1);
        assert!(p.cell_visible(9) && !p.cell_visible(0), "SOLO draws only the selected cell");
    }
}
