#!/usr/bin/env python3
"""
tools/observatory_package.py — assemble the Observatory's five-file package (WO-020 INC3).

The distributed package is a directory of AT MOST five files (MODULE-BUILD-GUIDE §3, ADR-010 d5):

    instruments/observatory/
      sparqmod.toml        1 — GENERATED by instruments-src/observatory/gen_manifest.py (never edited)
      observatory.wasm     2 — the component: cargo build --release --target wasm32-unknown-unknown
                               + wasm-tools component new (recipe below; the sandbox proved it fits)
      example.sparqpatch   3 — hand-authored in instruments-src/observatory/package/ (§5.4)
      preview.svg          4 — VALIDATOR-GENERATED on a host with the runtime (stage 6); never
                               hand-drawn, never assembled here — its absence is advisory words
      README.md            5 — hand-authored in instruments-src/observatory/package/ (§11.3)

The cap governs the DISTRIBUTED package, not the source project: everything else (the three crates,
the generators, the coastline source, the fixtures) lives in instruments-src/ and never ships.

This tool copies, it does not invent: it refuses (in words) if the generated manifest is stale
(run gen_manifest.py --check first), if a hand-authored file is missing, or if the component is
missing — a package without its wasm fails validate stage 2 fatally, so assembling one would be
dishonest. The component's recipe (proven in the ~1 GB sandbox on 2026-10-06, plan §12.2):

    rustup target add wasm32-unknown-unknown
    cd instruments-src/observatory
    cargo build --release --target wasm32-unknown-unknown -p observatory-wasm
    wasm-tools component new target/wasm32-unknown-unknown/release/observatory_wasm.wasm \\
        -o observatory.wasm            # wasm-tools ≥ 1.261; the embedded WIT needs no --wit flag

Usage:
    python3 tools/observatory_package.py --component path/to/observatory.wasm
    python3 tools/observatory_package.py --component … --out instruments/observatory
    python3 tools/observatory_package.py --list        # what WOULD be assembled, from where
"""
from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys

# Windows consoles and redirected logs default to the ANSI code page (defect #37); every tool
# reconfigures its streams (tools/README.md -> 'Text I/O portability'; check_text_io.py gate).
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

ENCODING = "utf-8"
ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "instruments-src" / "observatory"
STAGE = SRC / "package"
DEFAULT_OUT = ROOT / "instruments" / "observatory"

# The hand-authored / generated sources of the package files (role -> staging path).
SOURCES = {
    "sparqmod.toml": STAGE / "sparqmod.toml",
    "example.sparqpatch": STAGE / "example.sparqpatch",
    "README.md": STAGE / "README.md",
}


def read_text(path) -> str:
    return pathlib.Path(path).read_text(encoding=ENCODING)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Assemble the Observatory five-file package (WO-020).")
    ap.add_argument("--component", type=pathlib.Path, help="the componentised observatory.wasm")
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT, help="package directory")
    ap.add_argument("--list", action="store_true", help="print the assembly plan and exit")
    args = ap.parse_args(argv)

    # The generated manifest must be fresh — a stale sparqmod.toml in a shipped package is a drift
    # bug with no symptom until a cell draws the wrong feed.
    gen = SRC / "gen_manifest.py"
    chk = subprocess.run(
        [sys.executable, str(gen), "--check"], capture_output=True, text=True, cwd=ROOT
    )
    if chk.returncode != 0:
        print("observatory_package: REFUSED — the generated manifest is stale:")
        print("  " + (chk.stdout or chk.stderr).strip().replace("\n", "\n  "))
        print("  fix: python3 instruments-src/observatory/gen_manifest.py && commit")
        return 1

    if args.list:
        print("observatory_package: assembly plan")
        for name, src in SOURCES.items():
            state = "ok" if src.is_file() else "MISSING"
            print(f"  {name:18} <- {src.relative_to(ROOT)} [{state}]")
        comp = args.component
        print(f"  {'observatory.wasm':18} <- {comp if comp else '(--component not given)'} "
              f"[{'ok' if comp and comp.is_file() else 'MISSING'}]")
        print(f"  {'preview.svg':18} <- (validator-generated on device; absent is advisory)")
        print(f"  -> {args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out}")
        return 0

    missing = [n for n, s in SOURCES.items() if not s.is_file()]
    if missing:
        print(f"observatory_package: REFUSED — missing source file(s): {', '.join(missing)}")
        return 1
    if not args.component or not args.component.is_file():
        print(
            "observatory_package: REFUSED — no --component given (or the file is absent).\n"
            "  A package without its wasm fails `sparq mod validate` stage 2 fatally, so this tool\n"
            "  will not assemble a half-package. Build it (recipe in this tool's docstring):\n"
            "    cargo build --release --target wasm32-unknown-unknown -p observatory-wasm\n"
            "    wasm-tools component new …/observatory_wasm.wasm -o observatory.wasm"
        )
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    # Clear any prior package so a retired role cannot linger as a sixth file.
    for old in args.out.iterdir():
        if old.is_file():
            old.unlink()
    for name, src in SOURCES.items():
        shutil.copyfile(src, args.out / name)
    shutil.copyfile(args.component, args.out / "observatory.wasm")

    files = sorted(p.name for p in args.out.iterdir() if p.is_file())
    print(f"observatory_package: assembled {args.out.relative_to(ROOT)} ({len(files)} files ≤ 5 cap):")
    for f in files:
        print(f"  {f:18} {(args.out / f).stat().st_size:>9} B")
    if len(files) > 5:
        print("observatory_package: FAIL — the sixth file is E-PACKAGE-FILECOUNT; the cap is contract")
        return 1
    print("  preview.svg        (absent — validator stage 6 generates it on device; advisory)")
    print("  next: cargo run -p sparq-app --features streams -- mod validate instruments/observatory/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
