#!/usr/bin/env python3
"""sparq sync stamp - prove the tree on THIS machine is the tree the sandbox built.

Why this tool exists (defect #78, SATURN, 2026-09-25)
-----------------------------------------------------
`test005` failed at step [01] with six rustc errors of one shape:

    error[E0599]: no method named `resolve_master` found for reference `&CanvasState`
    error[E0609]: no field `master` on type `CanvasState`
      = note: available fields are: `camera`, `selection`, `interaction`, `menu`, `history`

Every one of those items exists in the `crates/sparq-ui/src/canvas/interact.rs` that shipped in
`sync-wo013-inc2.zip`, and the six error line numbers match the shipped `sparq-app` files exactly -
so the app crate on the stage machine WAS the new one. The `available fields` note is the tell: it
lists inc1's `CanvasState`, five fields, no `master`. The compiler was reading **inc1's sparq-ui**.

Two mechanisms produce that, and from a build log alone they are indistinguishable:

  (a) the file never landed - the extraction skipped or partially applied;
  (b) the file landed and cargo did not look at it. Zip extraction restores the ARCHIVE's
      timestamps, so a freshly-synced source can be *older* than the cached build, cargo concludes
      "Fresh", and the previous increment's rlib is served to the crates that depend on it. This is
      defect #41's mechanism in a new place: #41/#49 were about a stale *binary* passing a run, so
      `build.bat` grew a stamp guard that checks the exe AFTER a successful build. A stale
      *dependency rlib* fails the compile instead, so the build never reaches the guard - the
      remedy and the detector were both on the wrong side of the failure.

Reproduced in the sandbox, measured (2 cores, release profile):

    build sparq-ui from inc1's interact.rs            1.28 s   (rlib written)
    put inc2's interact.rs in place, mtime = archive time
    cargo build --release -p sparq-ui -v             -> "Fresh sparq-ui", 0.06 s
       the rlib contains `resolve_master`  0 times
    rd .fingerprint\\sparq-*  &&  rebuild              4.20 s
       the rlib contains `resolve_master`  6 times

So this tool answers (a) by content, not by timestamp: `SYNC-STAMP.txt` (shipped in every sync zip,
generated by `--write`) holds the sha256 + byte size of every file that decides what the binary is.
`scripts\\build.bat` runs it BEFORE cargo, so a half-applied sync is named in words instead of
arriving as six errors from a crate that is not the one that is wrong. The remedy for (b) is
`--freshness`: build.bat compares the tree's content digest with a marker written after the last
good build and deletes the five first-party fingerprints when the two disagree - which is exactly
when cargo's mtime test cannot be trusted, and never when it can, so an unchanged tree still builds
incrementally in seconds.

Scope of the manifest: `crates/*/src/**/*.rs`, `crates/*/build.rs`, every `Cargo.toml`,
`modules/**` (the runtime-loaded manifests - `sparq modules --strict` and the registry-driven demo
graph read them), `scripts/*.bat`, `tools/*.py`, and the three toolchain config files. Documents are
deliberately excluded: a stale `.md` cannot break a build, and including 400 KB of prose would bury
the one line that matters. `Cargo.lock` is listed but SOFT - cargo rewrites it for its own reasons
and a difference there is worth reading, not worth blocking a build on.

Usage:
    python3 tools/sync_check.py             # full report, exit 1 on any mismatch
    python3 tools/sync_check.py --quiet     # verdict + offenders only (what build.bat runs)
    python3 tools/sync_check.py --json
    python3 tools/sync_check.py --write     # regenerate SYNC-STAMP.txt from this tree
    python3 tools/sync_check.py --self-test # prove every verdict fires (no repo needed)

Exit codes: 0 clean (warnings allowed) · 1 the tree does not match the stamp · 2 the check could not
run (no manifest, unreadable tree) - which callers must report loudly and never read as "clean".
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import sys
import tempfile

# --------------------------------------------------------------------------- text I/O
# Every text read and write in this tool is explicit about encoding and newline handling: on
# Windows `read_text()` defaults to the ANSI code page (cp1252 in the field) and `write_text()`
# translates "\n" to "\r\n", which is how a generated file comes to look stale against its own
# LF-only committed copy (defects #19/#37; enforced by tools/check_text_io.py).
ENCODING = "utf-8"

# Windows consoles and redirected logs default to the ANSI code page: printing the UTF-8 characters
# this project uses raises UnicodeEncodeError mid-report, and a report that dies hides its own
# findings (defect #37). Degrade visibly instead.
import sys as _sys

for _stream in (_sys.stdout, _sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):  # not a TextIOWrapper (captured/redirected oddly)
        pass


def read_text(path: pathlib.Path) -> str:
    """Read a text file as UTF-8, on every platform."""
    return path.read_text(encoding=ENCODING)


def write_text(path: pathlib.Path, text: str) -> None:
    """Write a text file as UTF-8 with LF endings, on every platform."""
    path.write_text(text, encoding=ENCODING, newline="\n")


# --------------------------------------------------------------------------- the covered set
ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = "SYNC-STAMP.txt"

# The five `src` roots the build fingerprint walks. This list is MIRRORED in three places and a
# change must be made in all three: `crates/sparq-app/build.rs` (which computes the stamp that goes
# into the binary), `scripts/build.bat`'s `:stamp_check` (which recomputes it in cmd), and here.
# Defect #68 was exactly that mirror drifting - build.rs walked five roots while build.bat walked
# four, and the guard would have condemned every fresh binary for a whole increment.
# SIX roots, mirroring build.rs and build.bat exactly (defect #68's rule: the three definitions
# change together). sparq-music joined when WO-009 gave the crate contents; a copy of this file
# that lost the entry produced a stamp whose `fp` line the device's build.bat could never
# reproduce (defect #86) - the covered set and the fingerprint both count the music crate.
FP_ROOTS = [
    "crates/sparq-kernel/src",
    "crates/sparq-audio/src",
    "crates/sparq-ui/src",
    "crates/sparq-module-api/src",
    "crates/sparq-music/src",
    "crates/sparq-app/src",
]

# Files whose difference is reported but does not fail the build.
SOFT = {"Cargo.lock"}

CRATE_DIRS = [
    "sparq-kernel",
    "sparq-audio",
    "sparq-ui",
    "sparq-module-api",
    "sparq-music",
    "sparq-app",
]
CONFIG_FILES = ["Cargo.toml", "rust-toolchain.toml", "clippy.toml", "rustfmt.toml"]


def covered_files(root: pathlib.Path) -> list[str]:
    """Every path the manifest must cover, repo-root-relative, POSIX separators, sorted.

    Globbing rather than a hand-maintained list is the point: a NEW source file that nobody added
    to a manifest still shows up, and then fails the `fp` line - which is the difference between a
    gate that catches the next increment and one that only catches the last one.
    """
    out: set[str] = set()
    for crate in CRATE_DIRS:
        src = root / "crates" / crate / "src"
        if src.is_dir():
            out.update(p.relative_to(root).as_posix() for p in src.rglob("*.rs"))
        for extra in ("build.rs", "Cargo.toml"):
            if (root / "crates" / crate / extra).is_file():
                out.add(f"crates/{crate}/{extra}")
    for cfg in CONFIG_FILES:
        if (root / cfg).is_file():
            out.add(cfg)
    if (root / "Cargo.lock").is_file():
        out.add("Cargo.lock")
    modules = root / "modules"
    if modules.is_dir():
        out.update(
            p.relative_to(root).as_posix()
            for p in modules.rglob("*")
            if p.is_file() and "target" not in p.parts
        )
    scripts = root / "scripts"
    if scripts.is_dir():
        out.update(p.relative_to(root).as_posix() for p in sorted(scripts.glob("*.bat")))
    tools = root / "tools"
    if tools.is_dir():
        out.update(p.relative_to(root).as_posix() for p in sorted(tools.glob("*.py")))
    return sorted(out)


def fingerprint(root: pathlib.Path) -> tuple[int, int]:
    """(count, bytes) of every `*.rs` under FP_ROOTS - the definition build.rs and build.bat use."""
    files = 0
    total = 0
    for rel in FP_ROOTS:
        base = root / rel
        if not base.is_dir():
            continue
        for path in base.rglob("*.rs"):
            if path.is_file():
                files += 1
                total += path.stat().st_size
    return files, total


def tree_digest(root: pathlib.Path) -> str:
    """One hash for the whole covered tree: paths, sizes, content, and the fingerprint.

    This is the number `build.bat` compares against the marker it wrote after the last SUCCESSFUL
    build, to decide whether cargo's fingerprint cache can be trusted. Cargo's own freshness test is
    mtime-based, and a zip extraction restores archive mtimes, so "the content changed" and "cargo
    will notice" are different questions (defect #78). This answers the first one, which is the one
    that matters; the purge it triggers answers the second.
    """
    files, total = fingerprint(root)
    h = hashlib.sha256()
    h.update(f"fp {files}f/{total}B\n".encode("utf-8"))
    for rel in covered_files(root):
        path = root / rel
        if path.is_file():
            h.update(f"{rel} {path.stat().st_size} {sha256_of(path)}\n".encode("utf-8"))
        else:
            h.update(f"{rel} MISSING\n".encode("utf-8"))
    return h.hexdigest()


def sha256_of(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:  # binary: encoding does not apply
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# --------------------------------------------------------------------------- the manifest
HEADER = """# sparq sync stamp - generated by `python tools/sync_check.py --write`. Do not edit by hand.
#
# The byte-exact content of every file that decides what the binary is. `scripts/build.bat` checks
# this BEFORE it asks cargo for anything, because a half-applied zip otherwise arrives as six rustc
# errors in a crate that is not the one that is wrong (defect #78). Read tools/sync_check.py's
# docstring for the two mechanisms it distinguishes; run `python tools/sync_check.py` for the
# per-file report, or `scripts\\synccheck.bat` for the same into logs\\synccheck.log.
#
# Documents are excluded on purpose: a stale .md cannot break a build, and 400 KB of prose would
# bury the one line that matters. `fp` mirrors build.rs and build.bat - all three must change
# together (defect #68).
"""


def write_manifest(root: pathlib.Path, sync: str, sent: str) -> int:
    """Regenerate SYNC-STAMP.txt from the tree. Returns the number of entries written."""
    paths = covered_files(root)
    files, total = fingerprint(root)
    lines = [
        HEADER.rstrip("\n"),
        "",
        f"sync {sync}",
        f"sent {sent}",
        f"fp {files}f/{total}B",
        "",
    ]
    for rel in paths:
        p = root / rel
        size = p.stat().st_size
        digest = sha256_of(p)
        # Three fields, space-separated, path last: `scripts/pack source.bat` has a space in it, so
        # anything that could follow the path would be ambiguous. Softness lives in the SOFT set
        # above, not in the data - one definition, nothing to drift.
        lines.append(f"{digest} {size} {rel}")
    write_text(root / MANIFEST, "\n".join(lines) + "\n")
    return len(paths)


class Entry:
    __slots__ = ("path", "sha", "size", "soft")

    def __init__(self, path: str, sha: str, size: int, soft: bool) -> None:
        self.path = path
        self.sha = sha
        self.size = size
        self.soft = soft


def read_manifest(root: pathlib.Path) -> tuple[list[Entry], str, str, str | None]:
    """Parse SYNC-STAMP.txt -> (entries, sync name, sent date, fp string or None)."""
    path = root / MANIFEST
    if not path.is_file():
        raise FileNotFoundError(str(path))
    entries: list[Entry] = []
    sync = "?"
    sent = "?"
    fp: str | None = None
    for raw in read_text(path).splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("sync "):
            sync = line[5:].strip()
            continue
        if line.startswith("sent "):
            sent = line[5:].strip()
            continue
        if line.startswith("fp "):
            fp = line[3:].strip()
            continue
        parts = line.split(" ", 2)
        if len(parts) != 3:
            continue
        sha, size_field, rel = parts
        try:
            size = int(size_field)
        except ValueError:
            continue
        entries.append(Entry(rel, sha, size, rel in SOFT))
    return entries, sync, sent, fp


# --------------------------------------------------------------------------- the check
def check(root: pathlib.Path) -> dict:
    """Compare the tree against the manifest. Never raises for a mismatch - only for 'cannot run'."""
    entries, sync, sent, stamped_fp = read_manifest(root)
    bad: list[dict] = []
    warn: list[dict] = []
    ok = 0
    eol_seen = False
    for e in entries:
        p = root / e.path
        if not p.is_file():
            item = {"verdict": "MISSING", "path": e.path, "detail": "not on disk", "soft": e.soft}
            (warn if e.soft else bad).append(item)
            continue
        size = p.stat().st_size
        digest = sha256_of(p)
        if digest == e.sha and size == e.size:
            ok += 1
            continue
        # A difference that is ONLY line endings is worth naming but not worth blocking on:
        # .gitattributes pins LF for every source type, so this can only appear if something
        # between the zip and the disk rewrote the file - and the content is still the content,
        # rustc does not care, and the binary's own stamp stays self-consistent because build.rs
        # and build.bat measure the same on-disk bytes this tool just read.
        disk = p.read_bytes()
        if hashlib.sha256(disk.replace(b"\r\n", b"\n")).hexdigest() == e.sha:
            eol_seen = True
            warn.append({"verdict": "EOL", "path": e.path, "soft": e.soft,
                         "detail": "identical after CRLF -> LF; line endings were rewritten in "
                                   "transit"})
            continue
        if size != e.size:
            verdict, detail = "SIZE", f"disk {size}B, stamp {e.size}B"
        else:
            verdict, detail = "HASH", f"same size ({size}B), different sha256"
        item = {"verdict": verdict, "path": e.path, "detail": detail, "soft": e.soft}
        (warn if e.soft else bad).append(item)

    stamped = {e.path for e in entries}
    for rel in covered_files(root):
        if rel not in stamped:
            warn.append({"verdict": "EXTRA", "path": rel, "detail": "on disk, not in the stamp",
                         "soft": False})

    files, total = fingerprint(root)
    live_fp = f"{files}f/{total}B"
    if stamped_fp is not None and stamped_fp != live_fp:
        item = {
            "verdict": "FP",
            "path": "src fingerprint",
            "detail": f"tree {live_fp}, stamp {stamped_fp} - a .rs file was added, removed or "
                      f"resized; this is the number the binary carries",
            "soft": False,
        }
        # If nothing else is wrong and something was EOL-drifted, the fingerprint differs for that
        # reason alone - a warning, not a verdict against the sync.
        if eol_seen and not bad:
            item["detail"] += " (every differing file is EOL-only, so this is the same drift)"
            warn.append(item)
        else:
            bad.append(item)
    return {
        "sync": sync,
        "sent": sent,
        "stamped_fp": stamped_fp,
        "live_fp": live_fp,
        "checked": len(entries),
        "ok": ok,
        "bad": bad,
        "warn": warn,
    }


# --------------------------------------------------------------------------- the report
CAP = 20  # a sync that never landed at all would list 119 files; the first 20 already say it


def report(res: dict, quiet: bool) -> int:
    """Print the verdict. Returns the exit code: 0 clean (warnings allowed), 1 tree != stamp."""
    bad, warn = res["bad"], res["warn"]
    if bad:
        print(f"sync_check: FAIL - this tree is NOT sync {res['sync']} "
              f"({len(bad)} file(s) differ from the stamp)")
        for item in bad[:CAP]:
            print(f"  {item['verdict']:8} {item['path']}")
            print(f"           {item['detail']}")
        if len(bad) > CAP:
            print(f"  ... and {len(bad) - CAP} more - the sync did not land, or landed in part")
        if not quiet:
            for item in warn:
                print(f"  warn {item['verdict']:8} {item['path']} - {item['detail']}")
        print()
        print("  remedy: re-extract the sync zip AT THE REPO ROOT, overwriting, then re-run.")
        print("          The list above is the definitive answer to 'did the sync land' - it is")
        print("          content, not timestamps, so cargo's freshness cache cannot fool it.")
        print("          To build anyway (a local edit you mean to keep):")
        print("              scripts\\build.bat --skip-sync-check")
        return 1
    if quiet:
        print(f"sync_check: OK - {res['ok']} files match sync {res['sync']}, "
              f"src {res['live_fp']}")
        if warn:
            print(f"sync_check: {len(warn)} warning(s) - run scripts\\synccheck.bat for the list")
        return 0
    print(f"sync_check: OK - sync {res['sync']} (sent {res['sent']})")
    print(f"  {res['ok']} of {res['checked']} stamped files match byte-for-byte")
    if res["stamped_fp"] == res["live_fp"]:
        print(f"  src fingerprint {res['live_fp']} - matches the stamp")
    else:
        print(f"  src fingerprint {res['live_fp']} (stamp says {res['stamped_fp']})")
    for item in warn:
        print(f"  warn {item['verdict']:8} {item['path']} - {item['detail']}")
    if not warn:
        print("  no extras, no line-ending drift, nothing soft differing")
    return 0


# --------------------------------------------------------------------------- self-test
def self_test() -> int:
    """Prove every verdict fires. A gate nobody has seen fail is a gate nobody trusts."""
    results: list[tuple[str, bool, str]] = []
    global CRATE_DIRS
    saved_crates = CRATE_DIRS
    CRATE_DIRS = ["sparq-ui"]  # the synthetic tree below has one crate, not six

    def build_tree(base: pathlib.Path) -> None:
        (base / "crates" / "sparq-ui" / "src" / "canvas").mkdir(parents=True)
        (base / "crates" / "sparq-ui" / "build.rs").parent.mkdir(parents=True, exist_ok=True)
        write_text(base / "crates" / "sparq-ui" / "src" / "canvas" / "interact.rs",
                   "pub struct CanvasState { pub master: Option<u32> }\n")
        write_text(base / "crates" / "sparq-ui" / "src" / "lib.rs", "pub mod canvas;\n")
        write_text(base / "crates" / "sparq-ui" / "Cargo.toml", "[package]\nname = \"sparq-ui\"\n")
        write_text(base / "Cargo.toml", "[workspace]\n")
        write_text(base / "Cargo.lock", "version = 4\n")
        (base / "scripts").mkdir(exist_ok=True)
        write_text(base / "scripts" / "build.bat", "@echo off\r\n")

    def run_case(name: str, mutate, expect_rc: int, expect_verdict: str | None) -> None:
        with tempfile.TemporaryDirectory() as td:
            base = pathlib.Path(td)
            build_tree(base)
            write_manifest(base, "selftest", "today")
            if mutate is not None:
                mutate(base)
            res = check(base)
            verdicts = {i["verdict"] for i in res["bad"]} | {i["verdict"] for i in res["warn"]}
            rc = 1 if res["bad"] else 0
            good = rc == expect_rc and (expect_verdict is None or expect_verdict in verdicts)
            results.append((name, good, f"rc={rc} verdicts={sorted(verdicts) or '-'}"))

    run_case("clean tree passes", None, 0, None)

    def one_byte(base: pathlib.Path) -> None:
        p = base / "crates" / "sparq-ui" / "src" / "canvas" / "interact.rs"
        write_text(p, read_text(p) + "// one byte changed\n")

    run_case("one appended comment is caught", one_byte, 1, "SIZE")

    def same_size(base: pathlib.Path) -> None:
        p = base / "crates" / "sparq-ui" / "src" / "lib.rs"
        write_text(p, "pub mod canvax;\n")  # same byte count, different content

    run_case("a same-size edit is caught", same_size, 1, "HASH")

    def delete(base: pathlib.Path) -> None:
        (base / "scripts" / "build.bat").unlink()

    run_case("a file that never landed is named", delete, 1, "MISSING")

    def crlf(base: pathlib.Path) -> None:
        p = base / "crates" / "sparq-ui" / "src" / "lib.rs"
        p.write_bytes(read_text(p).replace("\n", "\r\n").encode("utf-8"))

    run_case("line-ending drift warns, does not block", crlf, 0, "EOL")

    def extra_source(base: pathlib.Path) -> None:
        write_text(base / "crates" / "sparq-ui" / "src" / "stray.rs", "// new file\n")

    run_case("a new .rs trips the fingerprint", extra_source, 1, "FP")

    def soft_lock(base: pathlib.Path) -> None:
        write_text(base / "Cargo.lock", "version = 4\n# cargo rewrote me\n")

    run_case("Cargo.lock differing is soft", soft_lock, 0, "SIZE")

    # The freshness marker: build.bat's purge decision, and defect #78's exact shape - a file whose
    # content changed while its mtime went BACKWARDS, which is what a zip extraction produces.
    with tempfile.TemporaryDirectory() as td:
        base = pathlib.Path(td)
        build_tree(base)
        marker = str(base / "target" / "release" / ".sparq-tree")
        rc = main(["--root", str(base), "--freshness-write", marker, "--quiet"])
        results.append(("marker written after a good build", rc == 0, f"rc={rc}"))
        rc = main(["--root", str(base), "--freshness", marker])
        results.append(("unchanged content -> FRESH, no purge", rc == 0, f"rc={rc}"))
        f = base / "crates" / "sparq-ui" / "src" / "canvas" / "interact.rs"
        f.write_bytes(f.read_bytes().replace(b"pub master", b"pub maaster", 1))
        os.utime(f, (0, 0))  # mtime 1970: cargo would call this file ancient and skip it forever
        rc = main(["--root", str(base), "--freshness", marker])
        results.append(("one byte changed, mtime 1970 -> PURGE", rc == 1, f"rc={rc} (defect #78)"))
        marker_missing = str(base / "target" / "release" / "nope")
        rc = main(["--root", str(base), "--freshness", marker_missing])
        results.append(("no marker -> PURGE, never assume fresh", rc == 1, f"rc={rc}"))

    CRATE_DIRS = saved_crates
    print("sync_check --self-test")
    failed = 0
    for name, good, detail in results:
        print(f"  {'PASS' if good else 'FAIL'}  {name:42} {detail}")
        if not good:
            failed += 1
    if failed:
        print(f"\n{failed} self-test case(s) failed - the gate is not trustworthy")
        return 1
    print(f"\nall {len(results)} cases behave: the gate is failable, and fires on each class")
    return 0


# --------------------------------------------------------------------------- main
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Verify the tree against SYNC-STAMP.txt")
    ap.add_argument("--root", default=None, help="repo root (default: inferred from this file)")
    ap.add_argument("--quiet", action="store_true", help="verdict + offenders only")
    ap.add_argument("--json", action="store_true", help="machine-readable report")
    ap.add_argument("--write", action="store_true", help="regenerate SYNC-STAMP.txt from this tree")
    ap.add_argument("--sync", default=None, help="with --write: the sync name to record")
    ap.add_argument("--sent", default=None, help="with --write: the date to record")
    ap.add_argument("--self-test", action="store_true", help="prove every verdict fires")
    ap.add_argument("--freshness", metavar="MARKER", default=None,
                    help="exit 0 if the tree's content digest equals MARKER's, 1 if it differs or "
                         "MARKER is missing - i.e. 1 means 'purge cargo's fingerprints'")
    ap.add_argument("--freshness-write", metavar="MARKER", default=None,
                    help="write the tree's content digest to MARKER (call after a good build)")
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()

    root = pathlib.Path(args.root).resolve() if args.root else ROOT
    if args.freshness_write:
        marker = pathlib.Path(args.freshness_write)
        digest = tree_digest(root)
        try:
            marker.parent.mkdir(parents=True, exist_ok=True)
            write_text(marker, digest + "\n")
        except OSError as exc:
            print(f"sync_check: could not write the freshness marker {marker}: {exc}")
            return 2
        if not args.quiet:
            print(f"sync_check: freshness marker written - {digest[:16]} -> {marker}")
        return 0
    if args.freshness:
        marker = pathlib.Path(args.freshness)
        digest = tree_digest(root)
        saved = None
        if marker.is_file():
            saved = read_text(marker).strip()
        if saved == digest:
            print(f"FRESH {digest[:16]}")
            return 0
        print(f"PURGE {digest[:16]}" + (f" != {saved[:16]}" if saved else " (no marker)"))
        return 1

    if args.write:
        sync = args.sync or "local"
        sent = args.sent or "unsent"
        n = write_manifest(root, sync, sent)
        files, total = fingerprint(root)
        print(f"sync_check: wrote {MANIFEST} - {n} files, src {files}f/{total}B, sync {sync}")
        return 0

    try:
        res = check(root)
    except FileNotFoundError:
        print(f"sync_check: CANNOT RUN - no {MANIFEST} at {root}")
        print("  This tree predates the stamp, or the sync that carries it did not land.")
        print("  Not a pass. Generate one with: python tools/sync_check.py --write --sync NAME")
        return 2
    if args.json:
        print(json.dumps(res, indent=2))
        return 1 if res["bad"] else 0
    return report(res, args.quiet)


if __name__ == "__main__":
    sys.exit(main())
